version: "3.3"
services:
  node1:
    image: grpc-product-demo
    build: .
    depends_on:
      - mongo
  node2:
    image: grpc-product-demo
    command: -n 1
    depends_on:
      - node1
  mongo:
    image: mongo:5
  nginx:
    image: nginx
    ports:
      - "9000:9000"
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node1
      - node2
